export const STORE_PAYMENT = 'STORE_PAYMENT';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_AS_SUCCESSFUL = 'UPDATE_PAYMENT_AS_SUCCESSFUL';
export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';